#!/bin/bash

# Setup script para Shipping Label System
# Autor: Generated by AI
# Data: $(date +%Y-%m-%d)

set -e

echo "🚀 Shipping Label - Setup Automático"
echo "======================================"
echo ""

# Cores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Função para imprimir com cores
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "ℹ $1"
}

# Verificar se Docker está rodando
print_info "Verificando Docker..."
if ! docker ps > /dev/null 2>&1; then
    print_error "Docker não está rodando!"
    print_warning "Iniciando Docker..."

    # Tentar iniciar Docker (WSL2)
    if command -v service &> /dev/null; then
        sudo service docker start
    else
        print_error "Por favor, inicie o Docker manualmente e execute este script novamente."
        exit 1
    fi

    # Aguardar Docker iniciar
    sleep 5

    if ! docker ps > /dev/null 2>&1; then
        print_error "Não foi possível iniciar o Docker. Por favor, inicie manualmente."
        exit 1
    fi
fi
print_success "Docker está rodando"

# Verificar se docker-compose está instalado
print_info "Verificando Docker Compose..."
if ! command -v docker-compose &> /dev/null; then
    print_error "Docker Compose não está instalado!"
    exit 1
fi
print_success "Docker Compose encontrado"

# Verificar se .env existe
if [ ! -f .env ]; then
    print_warning "Arquivo .env não encontrado. Criando..."
    if [ -f .env.example ]; then
        cp .env.example .env
        print_success "Arquivo .env criado a partir de .env.example"
    else
        print_error "Arquivo .env.example não encontrado!"
        exit 1
    fi
else
    print_success "Arquivo .env encontrado"
fi

# Parar containers existentes (se houver)
print_info "Parando containers existentes..."
docker-compose down > /dev/null 2>&1 || true
print_success "Containers parados"

# Build e iniciar containers
print_info "Construindo e iniciando containers..."
print_warning "Isso pode levar alguns minutos na primeira vez..."
docker-compose up -d --build

if [ $? -eq 0 ]; then
    print_success "Containers iniciados com sucesso"
else
    print_error "Erro ao iniciar containers"
    exit 1
fi

# Aguardar MySQL estar pronto
print_info "Aguardando MySQL inicializar..."
sleep 15

# Verificar se MySQL está saudável
MAX_ATTEMPTS=30
ATTEMPT=0
while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
    if docker-compose ps mysql | grep -q "healthy"; then
        print_success "MySQL está pronto"
        break
    fi

    ATTEMPT=$((ATTEMPT + 1))
    if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
        print_error "MySQL não ficou pronto a tempo"
        print_info "Verifique os logs com: docker-compose logs mysql"
        exit 1
    fi

    echo -n "."
    sleep 2
done
echo ""

# Executar migrations
print_info "Executando migrations..."
docker exec -it shipping_app php artisan migrate --force

if [ $? -eq 0 ]; then
    print_success "Migrations executadas com sucesso"
else
    print_warning "Erro ao executar migrations (pode ser normal se já estiverem executadas)"
fi

# Limpar caches
print_info "Limpando caches..."
docker exec shipping_app php artisan config:clear > /dev/null 2>&1
docker exec shipping_app php artisan cache:clear > /dev/null 2>&1
docker exec shipping_app php artisan route:clear > /dev/null 2>&1
print_success "Caches limpos"

# Resumo final
echo ""
echo "======================================"
echo "🎉 Setup concluído com sucesso!"
echo "======================================"
echo ""
print_info "Serviços disponíveis:"
echo "  🐘 Laravel API:  http://localhost:8000"
echo "  🌐 Nginx:        http://localhost:80"
echo "  🗄️  MySQL:        localhost:3306"
echo ""
print_info "Credenciais MySQL:"
echo "  Database: shipping_label"
echo "  Username: shipping_user"
echo "  Password: shipping_pass"
echo ""
print_info "Comandos úteis:"
echo "  docker-compose ps              # Ver status"
echo "  docker-compose logs -f         # Ver logs"
echo "  docker exec -it shipping_app bash  # Entrar no container"
echo "  docker-compose down            # Parar tudo"
echo ""
print_success "Acesse http://localhost:8000 para ver sua aplicação!"
echo ""

